import Info from "../../../components/UI/itemDetail/Info"
import Overview from "../../../components/UI/itemDetail/Overview";
import GarantiSection from "../../../components/layout/garantiSection/GarantiSection";
import styles from '../../../styles/Home.module.css';
import CommentSection from "../../../components/UI/commentSection/CommentSection";
import { useRouter } from "next/router";
import { allItems } from "../../../lib/Items";
import { useCart } from "react-use-cart";
import Head from 'next/head';


const ItemId = ()=>{
    const router = useRouter();
    const { addItem } = useCart();

    const card = allItems.find(item => item.id === parseInt(router.query.itemId));
//    allItems.map((item,index)=>{
//            if(item.id === parseInt(router.query.itemId)){
//                card = item;
//            }
//     });
    // const itemComment = card.comments;
    return(
        <div>
      
                <div className={styles.detailWrapper}>
                    <Head>
                        {/* <title>{card.title}</title> */}
                        {/* <meta name="item" content="Generated by rApToR" /> */}
                    </Head>
                    <Overview item={card} add={()=>addItem(card)}/>
                    <Info />
                    <GarantiSection />
                    <CommentSection comments={card}/>
                </div>)
      
      </div> 
    );
}
export default ItemId;