import Info from "../../../components/UI/itemDetail/Info"
import Overview from "../../../components/UI/itemDetail/Overview";
import GarantiSection from "../../../components/layout/garantiSection/GarantiSection";
import styles from '../../../styles/Home.module.css';
import CommentSection from "../../../components/UI/commentSection/CommentSection";
import { useRouter } from "next/router";
import { allItems } from "../../../lib/Items";
import { useCart } from "react-use-cart";
import { useState } from "react";


export async function getStaticPaths() {
    const paths = allItems.map(item =>({
        params: {itemId: item.id.toString()},
    }))
    // const fileNames = fs.readdirSync(allItems.map(item=>([item.id,])));
    return {
     paths,
        fallback: false
    };

  }
  
  export async function getStaticProps({ params }) {
    // Fetch necessary data for the blog post using params.id
    const postData = allItems.find(item => params.itemId === item.id.toString());
    
    // console.log(allItems);
    return {
      props: {
        postData,
      },
    };
  }



const ItemId = ({postData, params})=>{
    const router = useRouter();
    console.log(postData);
    
    // console.log(postData);
  
    const { addItem } = useCart();
    // let card;
    // card = allItems.find(item => item.id === parseInt(router.query.itemId));

    if (router.isFallback) {
        return <div>Loading...</div>;
      }
    return(
                <div className={styles.detailWrapper}>
                    {/* <Head> */}
                        {/* <title>{card.title}</title> */}
                        {/* <meta name="item" content="Generated by rApToR" /> */}
                    {/* </Head> */}
                    <Overview item={postData} add={()=>addItem(postData)}/>
                    <Info />
                    <GarantiSection />
                    <CommentSection comments={postData}/>
                </div>
    );
}
export default ItemId;