import Head from 'next/head'
import MainCarousel from '../components/UI/carousel/MainCarousel';
import styles from '../styles/Home.module.css'
import GarantiSection from '../components/layout/garantiSection/GarantiSection';
import MainSection from '../components/layout/main/MainSection';
import { Fragment } from "react";

export default function Home() {

  const imgs = [ {title: "first One", url:"/static/img/firstSlide.jpg"},
  {title: "first One", url:"/static/img/firstSlide.jpg"},
  {title: "first One", url:"/static/img/firstSlide.jpg"}, ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Sven shop</title>
        <meta name="description" content="Generated by rApToR" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainCarousel />
      <MainSection />
      <GarantiSection />     
    </div>
  )
}
